name:                vsc
version:             0.1.0.0
github:              "githubuser/vsc"
license:             BSD3
author:              "ThoNohT"
maintainer:          "e.c.p.bataille@gmail.com"
copyright:           "2021 ThoNohT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Visual Studio Code profile management tool
category:            Terminal

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ThoNohT/vsc#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  vsc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  vsc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vsc
